# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "freebsd/FreeBSD-12.0-CURRENT"
  config.vm.box_version = "2017.04.05"
  config.vm.base_mac = "08:00:27:d1:cc:74"

  config.vm.box_check_update = false
end
