# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "freebsd/FreeBSD-12.0-CURRENT"
  config.vm.box_version = "2017.04.05"
  config.vm.box_check_update = false

  config.vm.base_mac = "08:00:27:d1:cc:74"
  config.vm.synced_folder ".", "/vagrant/", disabled: true
  config.vm.synced_folder "./scripts/", "/vagrant/scripts", type: "rsync"
  # config.vm.synced_folder "~/Library/Application Support/minecraft/saves/Backups/", "/vagrant/backups", type: "rsync"

  config.ssh.shell = "sh"

  config.vm.provider "virtualbox" do |vb|
    vb.name = 'freebsd-zfs'

    current_dir = File.dirname(File.expand_path(__FILE__))
    file_to_disk = File.join(current_dir, 'disk.vdi')

    if not File.exist?(file_to_disk)
      vb.customize ['createhd', '--filename', file_to_disk, '--size',  20 * 1024]
    end
    vb.customize ['storageattach', :id, '--storagectl', 'IDE Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', file_to_disk]
  end

  config.vm.provision "shell", inline: <<-SHELL
    freebsd-update fetch
    freebsd-update install
    pkg update -f
    pkg upgrade -f
    pkg install -y fish git neovim
    chsh -s /usr/local/bin/fish vagrant
    cd /home/vagrant/
    su vagrant -c "git init"
    su vagrant -c "git remote add origin https://github.com/NicholasTD07/dotfiles.git"
    su vagrant -c "git pull origin master"
  SHELL
end
