# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "freebsd/FreeBSD-11.0-STABLE"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.ssh.shell = "/usr/local/bin/fish"
  config.ssh.shell = "sh"

  # config.vm.provider "virtualbox" do |vb|
  #   vb.gui = true
  # end
  config.vm.base_mac = "08:00:27:d1:cc:74"

  config.vm.provision "shell", inline: <<-SHELL
    freebsd-update fetch
    freebsd-update install
    pkg update -f
    pkg upgrade -f
    pkg install -y fish git neovim
    chsh -s /usr/local/bin/fish vagrant
    cd /home/vagrant/
    su vagrant -c "git init"
    su vagrant -c "git remote add origin https://github.com/NicholasTD07/dotfiles.git"
    su vagrant -c "git pull origin master"
  SHELL
end
